### ISSUE TITLE
Add appropriate disclaimer when people deploy via configuratior

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-configurator#14]
As we agreed on [Twitter ](https://twitter.com/MrKukks/status/1216033137114959872?s=20)in January, there needs to be a warning of some sort that's not super-scary but educates people on possible attack vectors.

**Comment by Kukks** [comment]
There already is. Added it after we discussed it.

**Comment by pavlenex** [comment]
@Kukks Hah, am I blind? I don't see it on install.btcpayserver.org?

**Comment by pavlenex** [comment]
Ah! I am. Need a coffee before I open GH. ☕ 
![warrning](https://user-images.githubusercontent.com/36959754/96417353-7608a280-11f1-11eb-8b89-7dc015e37cd2.PNG)
