### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-configurator#2]
I'll keep this issue for small UX related feedback gathered across multiple sources (Twitter, Mattermost, etc)
- [ ] Merge steps 3 and 4 (On and off-chain)
- [ ] put alts in advanced/geeky
- [ ] add CTA for the last step bellow the gif (gif does not have to be CTA/clickable)
- [ ] typo c-Lightning instead of CLightning

**Comment by Kukks** [comment]
Started looking into it but:
` put alts in advanced/geeky` can't be done: I need both choices in the same page as a user needs to have at least one chain chosen to be deployed. Else, the UX suffers from multi-page validation.

**Comment by Kukks** [comment]
Tried to ` Merge steps 3 and 4 (On and off-chain)` but it just looked messy as the page got longer

**Comment by pavlenex** [comment]
Well I still think 3 and 4 should be merged, perhaps reducing the size of that logo which seems unnecessary large may help?

**Comment by britttttk** [comment]
Awesome feature :) 

- I had a hard time seeing the first page was 2 buttons (dumb I know). So I was pressing continue without selecting one, it says ssh error but there was nothing shown about ssh on the page yet.
- Last page gif also does not look like a button and is scary.
- Sometimes the back button cant go back

Other than that, I thought everything looked really good! 

Other thoughts:
> Merge steps 3 and 4 (On and off-chain)

nack - simple page is better and less intimidating. Also LN page looks really pretty to me.

 >put alts in advanced/geeky

I prefer the choice to not use altcoins happens right away...  and to keep advanced/geeky free of alts.
