### ISSUE TITLE
Show warning when connecting to a remote node usign ssh credentials

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-configurator#7]

**Comment by pavlenex** [comment]
In the warring would advise people to run this locally. install.btcpayserver.org can become a honeypot, so the warning should really be prominent.

@rockstardev had some ideas on the warning .

Basically I'd tell them:
- you're using configurator at your own risk
- document the risks 
- tell the configurator is open-source
- tell for best practice it should be run locally
